introduction/urls.py
from django.urls import path
from . import views

app_name = 'introduction'
urlpatterns = [
    path('', views.profile, name="profile"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduction/', include('introduction.urls')),
    path('', views.main, name="main"),
    path('posts/', include('posts.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import new, create, main, show, update, delete

app_name = "posts"
urlpatterns = [
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('', main, name="main"),
    path('show/<int:id>', show, name="show"),
    path('update/<int:id>/', update, name="update"),
    path('delte/<int:id>/', delete, name = "delete"),
]

introduction/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
 
# Create your models here.
 
class Post(models.Model):
    title = models.CharField(max_length=50, null=False)
    content = models.TextField()    
    view_count = models.IntegerField(default = 0)    
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    image = models.ImageField(upload_to='images/',null=True)

introduction/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request, 'introduction/profile.html')

myblog/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'main.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post


def new(request):
    return render(request, 'posts/new.html')


def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        Post.objects.create(title=title,content=content,image=image)
        return redirect('main')

def main(request):
    posts = Post.objects.all()
    return render(request, 'posts/main.html', {'posts': posts})


def show(request, id):
    post = Post.objects.get(pk=id)
    return render(request, 'posts/show.html', {'post': post})


def update(request,id):
    post = get_object_or_404(Post,pk=id)
    if request.method == "POST":
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.image = request.FILES.get('image') 
        post.save()
        return redirect('posts:show',post.id)
    return render(request, 'posts/update.html',{"post":post})


def delete(request,id):
    post = get_object_or_404(Post,pk=id)
    post.delete()
    return redirect("posts:main")

introduction/templates/introduction/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>자기소개 페이지</h1>
{% endblock %}

myblog/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    <title>My Blog</title>
  </head>
  <body>
    
    {% include 'shared/_navbar.html' %}
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

myblog/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>메인 페이지</h1>
<img src="{% static 'images/lion.jpg' %}" alt="프로필이미지">
{% endblock %}

myblog/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'main' %}">Myblog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'introduction:profile' %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:new' %}">새글 쓰기</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:main' %}">글 목록</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </nav>

posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1>글 목록입니다.</h1>
        <div class="row">
            {% for post in posts %}
                <div class="col-md-4 col-12">
                    <div class="card" style="width: 18rem; margin-top: 20px;">
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="card-text">{{ post.content }}</p>
                            <p>{{ post.created_at }}</p>
                            <a href="{% url 'posts:show' post.pk %}" class="btn btn-primary">상
                            세보기</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>
        새로운 글 작성하기
    </h1>
    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
    <label>글 제목</label>
    <input type="text" class="form-control" name="title">
    </div>
    <div class="form-group">
    <label>글 내용</label>
    <textarea class="form-control" name="content"></textarea>
    <input type="file" name ="image">
    </div>
    <input type="submit" value="글 작성" class="btn btn-outline-primary">
    </form>
</div>
{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}
{% block content %}
<h1>상세보기 페이지</h1>
<h3>글 제목 : {{ post.title }} </h3><br>
<h3>글 내용 : {{ post.content }} </h3><br>
<h3>작성 시각 : {{ post.created_at }} </h3><br>
<h3>수정 시각 : {{ post.updated_at }} </h3><br>
<a href = "{% url 'posts:update' post.pk %}">수정하기</a>
<a href = "{% url 'posts:delete' post.pk %}">삭제하기</a>

    {% if post.image %}
        <img src ="{{ post.image.url }}">
    {%  endif %}
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>
        새로운 글 작성하기
    </h1>
    <form action="{% url 'posts:update' post.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
    <label>글 제목</label>
    <input type="text" class="form-control" name="title" value= "{{post.title}}">
    </div>
    <div class="form-group">
    <label>글 내용</label>
    <textarea class="form-control" name="content">{{post.content}}</textarea>
    </div>
    <input type="submit" value="글 수정" class="btn btn-outline-primary">
    <input type="file" name ="image">
    </form>
</div>
{% endblock %}